"""empty message

Revision ID: 0b20156b756c
Revises: 119d87952e8f
Create Date: 2022-02-18 16:53:23.428481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b20156b756c'
down_revision = '119d87952e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_lineup',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['Shows.id'], ),
    sa.PrimaryKeyConstraint('show_id', 'artist_id')
    )
    op.add_column('Shows', sa.Column('name', sa.String(length=25), nullable=False))
    op.alter_column('Shows', 'show_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('Shows_artist_id_fkey', 'Shows', type_='foreignkey')
    op.drop_column('Shows', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Shows_artist_id_fkey', 'Shows', 'Artist', ['artist_id'], ['id'])
    op.alter_column('Shows', 'show_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('Shows', 'name')
    op.drop_table('show_lineup')
    # ### end Alembic commands ###
