"""empty message

Revision ID: 119d87952e8f
Revises: be99acde292d
Create Date: 2022-02-17 03:58:29.926398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119d87952e8f'
down_revision = 'be99acde292d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('Shows', sa.Column('show_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'Shows', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Shows', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_column('Shows', 'show_time')
    op.drop_column('Shows', 'venue_id')
    op.drop_column('Shows', 'artist_id')
    # ### end Alembic commands ###
